### ISSUE TITLE
Error running WebGPT

### ISSUE THREAD

**Issue by gordingin** [Farzad-R/LLM-Zero-to-Hundred#21] opened 2024-10-19 15:33 UTC
after Python 3.11 install with pip install -r, I run streamlit run src\webgpt_app.py and receive the following error

Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.

Error: Invalid value: File does not exist: srcwebgpt_app.py

thx

**Comment by Farzad-R** [comment] 2024-10-19 18:21
1. Make sure you're using the correct path format for your platform. For example, on macOS or Linux, use `src/webgpt_app.py`, and on Windows, you can either use `src\webgpt_app.py` or `src/webgpt_app.py`.

2. Make sure you are running the command from the correct working directory where the src folder is located. If you're in the wrong directory, it won't find the file.

After cloning the repository, you can navigate to the correct directory with:
```
cd LLM-Zero-to-Hundred/WebGPT
```

**Comment by gordingin** [comment] 2024-10-19 20:54
First off sorry, I didn't look too closely at the file name/path and now I see the issue. I just assumed a file was missing. So the path you include is Windows base, I am on a MAC.  So the slash was removed. 

So
- Windows  = streamlit run src\webgpt_app.py
-  MAC = streamlit run src/webgpt_app.py

Small nuance

**Comment by Farzad-R** [comment] 2024-10-19 22:45
Glad to hear the issue is solved. I will close it then.

**Closed as completed by Farzad-R** 2024-10-19 22:45 UTC
